### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by ximlu** [securevale/swift-confidential#1]
Hello, I have read the documentation of your library, but I'm still not clear about how to use it. I want to obfuscate Swift code, and I'm not sure what the generated Confidential.generated.swift file is for. Does your library only handle constants in the code, or can it obfuscate the entire code? Do you have any sample projects or examples?

**Comment by mgutski** [comment]
Hi @ximlu, the short answer is: no, you cannot use Swift Confidential to obfuscate Swift code per se.

Swift Confidential, as stated in the repository description and README, is a Swift *literals* obfuscator, and as such it was designed to be used for obfuscating fixed values (currently, strings and arrays of strings are supported) that you reference in your source code. With that said, you can use it to obfuscate the selected literals that you specify in the `confidential.yml` configuration file, but you cannot use it to obfuscate the symbols (i.e. the code itself).

As for the sample project, there is a plan to create a sample iOS app that would showcase the use of Swift Confidential (and much more) + an interactive DocC tutorial. Hopefully then it will be easier for everyone to understand how to make the best use of our Open Source projects.

**Comment by mgutski** [comment]
Closing as there are no further comments or questions from the issue's author.

**Comment by trinhtran-markany** [comment]
Hi @mgutski , same question here. I don't know how to generate **Confidential.generated.swift** file. Could you help to provide the detail?

**Comment by trinhtranduc** [comment]
Hi @mgutski  , same question here. I don't know how to generate **Confidential.generated.swift** file. Could you help to provide the detail?

**Comment by mgutski** [comment]
Hello @trinhtranduc, I need more context to be able to help you. Could you perhaps tell me what setup are you trying to achieve and which part of the [Getting started](https://github.com/securevale/swift-confidential#getting-started) guide are you having trouble with?

**Comment by trinhtranduc** [comment]
Hi @mgutski , thanks for your response. I'm able to integrate the library successfully now. If you don't mind, please help me another situation. Assume, i have an example below:

```
enum Environment: String{
    case development = "Development"
    case staging = "Staging"
    case production = "Production"
}
```

Does the library support as below? If not, do you have any suggestion?

```
enum Environment: String{
    case development = Secrets.$development
    case staging = Secrets.$staging
    case production = Secrets.$production
}
```

Thanks
