### ISSUE TITLE
Build swift-confidential and plugin From Source

### ISSUE THREAD

**Issue by ekam123** [securevale/swift-confidential#2]
Hello, 

Is there any tutorial or documentation for how to build ConfidentialKit manually from the source files to add to a project? Or are there any plans to have different releases outside of SPM?
I was creating a framework and added swift-confidential and swift-confidential-plugin and everything works as expected. But when I add my framework to a test iOS app, I get 'Missing required modules ConfidentialKit.' I don't want to have to rely on the parent app to manually add the packages too in addition to my framework.

**Comment by mgutski** [comment]
Hi @ekam123, 

Based on your issue description, it looks like you stumbled upon a problem that was addressed in the [latest release of Swift Confidential](https://github.com/securevale/swift-confidential/releases/tag/0.3.0).

In short, the solution is to enable implementation-only `ConfidentialKit` import, which you can do by adding `implementationOnlyImport: true` somewhere at the root level of your `confidential.yml` configuration file. This will hide the `ConfidentialKit` symbols from your library consumers and the aforementioned compiler error should go away. See [Building libraries for distribution](https://github.com/securevale/swift-confidential#building-libraries-for-distribution) section for more details.

Additionally, if you are importing `ConfidentialKit` manually somewhere in your library code (i.e. outside the generated `Confidential.generated.swift` file), then you will also need to annotate that import with `@_implementationOnly` attribute (but you prolly don't have such imports). As a matter of fact, the same technique applies to all the other potential dependencies of your framework that you don't want to be included in the module interface file that describes the framework's public API.

Hopefully, with the above configuration you will be able to achieve the desired framework integration experience. Let me know how it goes.

**Comment by ekam123** [comment]
Hi @mgutski 

I've added `implementationOnlyImport: true` to the top of confidential.yml file. It builds properly on a test app if the test app and framework are built on the same laptop. But if I add the framework alone to an app on a different laptop, then I get the missing module error. I think I'll have to look more into building the framework properly. 

Thanks.
